<?php 
	get_header();
	get_template_part('inc/slider');
	get_template_part('inc/home-intro');
	get_template_part('inc/home-services');
	get_template_part('inc/home-what-we-do-banner');
	get_template_part('inc/home-testimonials');
	//get_template_part('inc/home-logo-slider');
	get_footer(); 
?>
